/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kopapirollo;

import java.util.Random;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author ViczaiPéterMilán(Szf
 */
public class KoPapirOllo extends javax.swing.JFrame {

    /**
     * Creates new form KoPapirOllo
     * 
     */
    
    Random rnd = new Random();
    Scanner sc = new Scanner(System.in);
    
    public KoPapirOllo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        emberPapir = new javax.swing.JRadioButton();
        emberOllo = new javax.swing.JRadioButton();
        emberKo = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kő, papír, olló játék");

        logArea.setColumns(20);
        logArea.setRows(5);
        logArea.setText("Kő, papír, olló játék!");
        jScrollPane1.setViewportView(logArea);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Választás"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ember"));

        buttonGroup1.add(emberPapir);
        emberPapir.setText("Papír");
        emberPapir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emberPapirActionPerformed(evt);
            }
        });

        buttonGroup1.add(emberOllo);
        emberOllo.setText("Olló");
        emberOllo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emberOlloActionPerformed(evt);
            }
        });

        buttonGroup1.add(emberKo);
        emberKo.setText("Kő");
        emberKo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emberKoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emberKo)
                    .addComponent(emberPapir)
                    .addComponent(emberOllo))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(emberKo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emberPapir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emberOllo)
                .addContainerGap())
        );

        jButton1.setText("Indít");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        logArea.setText("");
        if (!emberOllo.isSelected() && !emberPapir.isSelected() && !emberKo.isSelected()) {
            JOptionPane.showMessageDialog(this, "Kérlek, válassz egy lehetőséget!", "Hiba", JOptionPane.ERROR_MESSAGE);
        return;
        }
        String jatekostipp = "";
        int geptipp = rnd.nextInt(3) + 1;
        logArea.append("A gép is választott!\n");
        

        if (emberKo.isSelected()) {
            jatekostipp = "Kő"; // 1
        } else if (emberPapir.isSelected()) {
            jatekostipp = "Papír"; // 2
        } else if (emberOllo.isSelected()) {
            jatekostipp = "Olló"; // 3
        }
        
        if (jatekostipp == "Kő" && geptipp == 1){
            logArea.append("Döntetlen!\n");
        } else if (jatekostipp == "Kő" && geptipp == 2) {
            logArea.append("A gép nyert!\n");
        } else if (jatekostipp == "Kő" && geptipp == 3) {
            logArea.append("A játékos nyert!\n");
        } else if (jatekostipp == "Papír" && geptipp == 1) {
            logArea.append("A játékos nyert!\n");
        } else if (jatekostipp == "Papír" && geptipp == 2) {
            logArea.append("Döntetlen!\n");
        } else if (jatekostipp == "Papír" && geptipp == 3) {
            logArea.append("A gép nyert!\n");
        } else if (jatekostipp == "Olló" && geptipp == 1) {
            logArea.append("A gép nyert!\n");
        } else if (jatekostipp == "Olló" && geptipp == 2) {
            logArea.append("A játékos nyert!\n");
        } else if (jatekostipp == "Olló" && geptipp == 3) {
            logArea.append("Döntetlen!\n");
        }
        
        logArea.append("A játéknak vége!");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void emberKoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emberKoActionPerformed
        logArea.setText("");
        logArea.append("Az ember a követ választotta\n");
    }//GEN-LAST:event_emberKoActionPerformed

    private void emberPapirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emberPapirActionPerformed
        logArea.setText("");
        logArea.append("Az ember a papírt választotta\n");
    }//GEN-LAST:event_emberPapirActionPerformed

    private void emberOlloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emberOlloActionPerformed
        logArea.setText("");
        logArea.append("Az ember az ollót választotta\n");
    }//GEN-LAST:event_emberOlloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KoPapirOllo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KoPapirOllo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KoPapirOllo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KoPapirOllo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KoPapirOllo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton emberKo;
    private javax.swing.JRadioButton emberOllo;
    private javax.swing.JRadioButton emberPapir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logArea;
    // End of variables declaration//GEN-END:variables
}
